[font]
normal = { family = "Caskaydia Mono Nerd Font", style = "Regular" }
italic= { family = "Caskaydia Mono Nerd Font Propo", style = "Italic" }
bold_italic = { family = "Caskaydia Mono Nerd Font Propo", style = "Semibold Italic" }
bold = { family = "Caskaydia Mono Nerd Font", style = "Bold" }
size = 15
